version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: customerManagement-postgres
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: